[build]
  command = "yarn install && npx prisma generate && yarn build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  PRISMA_CLI_QUERY_ENGINE_TYPE = "binary"

[[plugins]]
  package = "@netlify/plugin-nextjs"
